### ISSUE TITLE
Quest book bug

### ISSUE THREAD

**Issue by KuzenKrafts** [rockobonaparte/bfsr#5]
The nether chapter has a quest for making obsidian through the Tic smeltery. im assuming its a detection type quest. it requires a smeltery drain and a channel. it detected the channel but not the drain. Just thought id let you know if you don't already

**Comment by rockobonaparte** [comment]
Fixed now in 1362407b3643c50d95777562a8c4fa9ba1730a4e

I have no explanation for it. My speculation is that when I previously exported the quest book as text to edit it, this went awry. I have had all kinds of grief from that. I think you've seen some tools with goofy extra text in them too. Those are also artifacts from doing that. I had to reassign the detecting item. It worked after that.

If you're slick with GitHub, you can pull the latest config directory here and have it. It's all under config\hqm. Back up that folder in your instance, then overwrite it with the new files.
